### ISSUE TITLE
Difference Between "Deploy DB" and "Publish DB" Pipelines

### ISSUE THREAD

**Issue by JohnRGH** [DrJohnT/AzureDevOpsExtensionsForSqlServer#1]
What is the difference between these 2 pipeline components?

**Deploy Database DACPAC using a DAC Publish Profile**
https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.DeployDatabase&ssr=false#overview

**Publish DACPAC using a DAC Publish Profile**
https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.PublishDacPac&ssr=false#overview

**Comment by DrJohnT** [comment]
Nothing at all.  I published the "Publish DacPac" version first and then
realized that many people would search for "Deploy Database", so hence two
components.

John Tunnicliffe

Mobile: +44 7771 818770
john@bovi.co.uk

*Life is what you make it*

**Comment by bbakermmc** [comment]
So what version do we need?  I seems like publish is 1version higher than deploy?   Maybe you should just drop one of the packages and put the proper tags for searching.  Kinda confusing.
