### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by maroliict** [DrJohnT/AzureDevOpsExtensionsForSqlServer#10]
Is there a way we can use these products to deliver a database to over 100 instances?

**Comment by DrJohnT** [comment]
Interesting requirement!    Take a look at this blog which mentions the "Each" YAML component. https://mattvsts.github.io/2019/05/04/solving-the-looping-problem-in-Azure-DevOps-Pipelines/

Alternatively, you could write a PowerShell script that iterates over the server collection and uses my PowerShell module "Publish DacPac" https://www.powershellgallery.com/packages/PublishDacPac/
This is the same module my DevOps component uses to perform the deployment.
