### ISSUE TITLE
SSAS Extension issue on prem azure DevOps 2019

### ISSUE THREAD

**Issue by vinimehta** [DrJohnT/AzureDevOpsExtensionsForSqlServer#12]
Hello, 

When using the drop SSAS release task, we are getting the following error: 

2019-09-19T16:17:53.8666754Z ##[error]SSAS Server [Server name] not found. 

Is this extension compatible with On-Prem Azure DevOps Server?

Thank you, 
Vini

**Comment by vinimehta** [comment]
Hello, 

Is there any progress on this? 

Thank  you, 
Vini

**Comment by erwanlancien** [comment]
Hi, I have the same issue with IaaS SAAS Tabular server on azure.
When I use the cmdlets PowerShell DeployCube directly remotely from the SSAS server with the same identity as the devops agent, it works, but not within devops.
But the version  of the cmdlets delivered with devops seems older than the last release PowerShell CmdLets

**Comment by DrJohnT** [comment]
@vinimehta 
The version of Azure DevOps does not matter as the extension will work so long as Microsoft.AnalysisServices.Deployment.exe is installed on the agent.  I have removed some unnecessary checks from the extension, so you will not get this issue anymore.

**Comment by DrJohnT** [comment]
@erwanlancien 
The entire extension and supporting PowerShell modules have been republished.  Please check out the new version(s).
https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.DeployTabularModel
https://www.powershellgallery.com/packages/DeployCube/
