### ISSUE TITLE
Enhancement | Allow SQL Username and Password

### ISSUE THREAD

**Issue by BevanG** [DrJohnT/AzureDevOpsExtensionsForSqlServer#13]
Would it possible to pass through SQL Username and Password? This would allow the Extension to use both Integrated security (as it does now) and sql authentication with a minor change.

It could look something like: 
```
foreach ($SqlCmdFile in $SqlCmdFiles) {
	$Command = {Invoke-Sqlcmd -Server $Server -Database $Database -InputFile $SqlCmdFile -QueryTimeout $QueryTimeout -ErrorAction Stop}
	# Now Invoke-Sqlcmd for each script in the folder
	Write-Host "Running SQLCMD file:   $(Split-Path -Leaf $SqlCmdFile)"
	if ($SqlCmdVariableType -ne 'none') {
		$Command = "$Command -Variable $SqlCmdVariables"
	}
	if ($SqlCmdUsername -ne 'none') {
		$Command = "$Command -Username $Username -Password $Password"
	}	
	Invoke-Command -ScriptBlock $Command
}
```

**Comment by fakhrulhilal** [comment]
I was about asking the same issue. So adding this feature will be great.

**Comment by abdullahamjad786** [comment]
Hi Everyone, 
Can you tell is this issue fixed?
I want to add Sql Server Username and Password in this Task.
So what is Possible work around for it?

**Comment by DrJohnT** [comment]
This functionality has now been added to the extension.  Please use v1.1.x of the extension.
