### ISSUE TITLE
Error on Update SSAS tabular cube data source 

### ISSUE THREAD

**Issue by indiefunda** [DrJohnT/AzureDevOpsExtensionsForSqlServer#2]
Hey, 

thanks for your contribution, you have done an amazing job, 
I am trying to deploy a tabular cube 1400 model with your Azure addon and it succeeds but when I am using the task "Update SSAS tabular cube data source"  in order to change connection string of the data source (we have many environments as you guess) I get the following error 

"Cannot bind argument to parameter 'InputObject' because it is null."

It doesn't help much debugging the error but I would be glad if you have some ideas on that. 

Thanks,
Achilles

**Comment by DrJohnT** [comment]
Hey Achilles, glad you like the extension.  Took some time to create and document this plus the underpinning PowerShell module [DeployCube](https://github.com/DrJohnT/DeployCube).  How many data source connections does your model have?  My code finds the first one and replaces that.  I did consider providing a field to enter the name of the data source in the model, but the new 1400 model seems to auto-generate the name, so the developer may now know what the name of data source is.  

To debug, try doing the deployment using [Update-TabularCubeDataSource](https://github.com/DrJohnT/DeployCube/blob/master/docs/Update-TabularCubeDataSource.md) in my [DeployCube](https://github.com/DrJohnT/DeployCube) PowerShell module.  See [Update-TabularCubeDataSource](https://github.com/DrJohnT/DeployCube/blob/master/docs/Update-TabularCubeDataSource.md)

My  [DeployCube](https://github.com/DrJohnT/DeployCube) repository has a whole test suite, so you should be able to simply change the tests for Update-TabularCubeDataSource with your own model and server names. Run the tests using Invoke-Pester.

If you do not manage to debug, please post the DataSource section of the model's JSON here and I will take a look.

**Comment by indiefunda** [comment]
Hello John, 

actually we have just one data source but even though it is a 1400 model we are using the legacy mode of inserting data into our model. I guess this is where it gets complicated.
I will try to see what you are suggesting. 

Thanks :)

**Comment by DrJohnT** [comment]
@indiefunda 
I have recently done a lot of work on the Update Tabular Cube Data Source Task within the Deploy Tabular Model extension.  Please check it out.
