### ISSUE TITLE
Error - With Run SQLCMD Scripts in folder

### ISSUE THREAD

**Issue by sumateeka** [DrJohnT/AzureDevOpsExtensionsForSqlServer#30]
I keep getting "Value cannot be null" not sure which value.See the attached full log with error message
[Error.docx](https://github.com/DrJohnT/AzureDevOpsExtensionsForSqlServer/files/5816371/Error.docx)

**Comment by DrJohnT** [comment]
The error message reads "Value cannot be null. Parameter name: ServerInstance"

Please check how you have specified the Server parameter.   I have a feeling that there is a syntax error in your sever name which is causing Invoke-Sqlcmd to throw the error you see.  

For named instances, use the format ComputerName\InstanceName

For named instances with a port, use the format ComputerName\InstanceName,port

**Comment by sumateeka** [comment]
I have the server instance name like this  something.windows.net,1433

**Comment by sumateeka** [comment]
Any other way to know the more details abt the error? This is the server name i uses everywhere something.windows.net,1111. Not sure with this tool .

**Comment by DrJohnT** [comment]
I have updated the extension to fix your issue.  Previously I did not have specific tests to check the Azure connectivity.  I spent tonight writing some. 

However, the extension does not support the port in the server address.  

if you simply have the standard port (i.e. 1433) you can simply remove the ,1433 part from the name and all should work.  

Not exactly sure why the Invoke-SqlCmd does not like a port number, bit too late to check tonight.

Please get back to me if you are using a non-standard port.

**Comment by DrJohnT** [comment]
@sumateeka 
I managed to fix the issue, so the port number is no longer causing a problem.
Please ensure you are using version 1.1.8 or later of the extension.

By the way, are you using SQL Server Data Tools to develop your database model?   If not, I strongly suggest you do so.  Much better way of developing database applications.  You can then use my other extension [Publish DACPAC using a DAC Publish Profile](https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.PublishDacPac) to perform incremental deploys automatically.

**Comment by sumateeka** [comment]
> @sumateeka
> I managed to fix the issue, so the port number is no longer causing a problem.
> Please ensure you are using version 1.1.8 or later of the extension.
> 
> By the way, are you using SQL Server Data Tools to develop your database model? If not, I strongly suggest you do so. Much better way of developing database applications. You can then use my other extension [Publish DACPAC using a DAC Publish Profile](https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.PublishDacPac) to perform incremental deploys automatically.

**Comment by sumateeka** [comment]
Thank you so much!
