### ISSUE TITLE
[ENHANCMENT] Hidden Password Field

### ISSUE THREAD

**Issue by samuraifox1** [DrJohnT/AzureDevOpsExtensionsForSqlServer#39]
![image](https://user-images.githubusercontent.com/86284310/139021400-f90f7200-c9ce-42f3-aefe-c38794d0f74b.png)

**Component**
This repo covers four extensions for Azure DevOps.  Please be clear which extension you are talking about.  The short extension names are:
* RunSqlCmdScripts
* DeployTabularModel
* PublishDacPac
* DeployDatabase (technically the same as PublishDacPac but rebranded as people think 'Deploy' rather than 'Publish').

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DrJohnT** [comment]
You are expected to use a locked variable as described in the documentation.  Much more sensible approach.
