### ISSUE TITLE
This task is not converting datatype from int to float in one of my table.

### ISSUE THREAD

**Issue by Ashish-Jovial** [DrJohnT/AzureDevOpsExtensionsForSqlServer#40]
Hi Team,

I am using this task in Azure DevOps, this task was working perfectly since last week. But since last week it is behaving differently.

I have a table, in which a column datatype was [int], I had changed from [int] to [float] and performed the deployment. It didn't show any error but did not change the column's data type from [int] to [float].

Please help me to resolve this issue.

Regards
Ashish Jain
Email : ashishmca941066@gmail.com
Mobi : +919891106712

**Comment by DrJohnT** [comment]
I suggest you use Visual Studio to generate the deployment script and see what it is attempting to do.  Also, perhaps check your DacPac publish profile settings.

This is not a fault with my library, so closing the issue
