### ISSUE TITLE
Credentials in Cube Deployment

### ISSUE THREAD

**Issue by erbg** [DrJohnT/AzureDevOpsExtensionsForSqlServer#41]
Hello,

in the "Deploy SSAS tabular cube model" i cannot find any field passing the Credentials to deploy the Model to the Server.

Do i miss something?
How should this work?

![image](https://user-images.githubusercontent.com/23281925/141968348-8f4bd300-63fe-4c75-b30d-dae383061bc9.png)

**Comment by DrJohnT** [comment]
The DevOps agent should run under an account which has admin permissions on the SSAS server.
