### ISSUE TITLE
Azure Synapse is failing to perform the deployment giving error "type Microsoft.Data.Tools.Schema.Sql.SqlDwDatabaseSchemaProvider is not valid"

### ISSUE THREAD

**Issue by Ashish-Jovial** [DrJohnT/AzureDevOpsExtensionsForSqlServer#43]
I am working on Azure Synapse. I am able to build the Azure Synapse project successfully using the Azure CI pipeline's MS Build task.

But as I am trying to deploy Azure Synapse using the Azure CD pipeline, I am getting the following error.

Internal Error. The database platform service with type Microsoft.Data.Tools.Schema.Sql.SqlDwDatabaseSchemaProvider is not valid. You must make sure the service is loaded, or you must provide the full type name of a valid database platform service.

I am deploying the DacPac using the following task. I hope this should not be any concern.

**https://github.com/DrJohnT/AzureDevOpsExtensionsForSqlServer/tree/master/extensions/PublishDacPac**

This is a weird error because a couple of days ago same deployment was done successfully.

My Publish profile is below.

![image](https://user-images.githubusercontent.com/5494030/152474156-3f570eae-0fb8-492d-9955-a64ab710169b.png)

Please help!

**Comment by Ashish-Jovial** [comment]
I have answered this question on StackOverflow
https://stackoverflow.com/questions/70975380/azure-synapse-is-failing-to-perform-the-deployment-giving-error-type-microsoft/70981827#70981827

**Comment by DrJohnT** [comment]
Thanks for the update.  I don't have access to Azure Synapse in order to test, so I will simply close the issue
