### ISSUE TITLE
[BUG] newly upgrade OnPrev DevOps 2022.0.1 fails

### ISSUE THREAD

**Issue by DuckoDeath** [DrJohnT/AzureDevOpsExtensionsForSqlServer#48]
AzureDevOpsServer_20230418.1
Been using this extension for a long time, just upgraded DevOps, now fails with:

The term 'Invoke-Sqlcmd' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

any help would be appreciated

**Comment by DrJohnT** [comment]
Will depend on your build agent.  An in-house agent will require Powershell  SqlServer module installing:  https://www.powershellgallery.com/packages/SqlServer

Be sure to uninstall SqlPs (see https://github.com/DrJohnT/AzureDevOpsExtensionsForSqlServer/wiki/Build-Server-Setup#delete-the-microsoft-sql-server-powershell-environment-variable ) 

For Microsoft Agents in the cloud, not sure they will be able to contact your on-prem servers to perform the install

**Comment by DuckoDeath** [comment]
For the record, had to uninstall the existing SqlServer powertools, and reinstall the latest version....
