### ISSUE TITLE
Server does not exist error

### ISSUE THREAD

**Issue by bradwyoung** [DrJohnT/AzureDevOpsExtensionsForSqlServer#6]
I am getting a server does not exist error.  I have the Agent setup on my desktop computer and I can connect to the SQL Server from Management Studio from same computer.  I am unsure how to troubleshoot this further.

2019-06-18T03:31:31.4844507Z ##[error]Error: Server 'XXXXX.xxxxxx.us-east-2.rds.amazonaws.com' does not exist!

Also how do you recommend passing the SQL login password to the task.  I have the login in the publish.xml file.

**Comment by fakhrulhilal** [comment]
I've this problem too. But when I tried to execute SqlPackage manually (using the same SqlPackage.exe as produced in output log) with this command `Sqlpackage /Action:Publish /SourceFile:[path to dacpac produced in pipeline output] /Profile:[path to profile produced in pipeline output]`, it just works without error.

**Comment by binaryevents** [comment]
Hi,
I have the same error here on a on-premise devops deploying to a database in the same network. 
I also tried to deploy to the build agents localdb wich works fine.
@bradwyoung @fakhrulhilal: Have you found a solution or workaround?

**Comment by JourdanDixon** [comment]
Same issue here. On premise and I can connect to the server with other tasks. I've tried all versions of the server name as well.

**Comment by DrJohnT** [comment]
Last week I republished all the extensions and removed the check for the existence of the server before deployment.  Please raise a new bug if version 1.2.x does not work for you @JourdanDixon @fakhrulhilal @binaryevents @bradwyoung
