### ISSUE TITLE
Publish DACPAC - Does Target server name overwrite the connection string?

### ISSUE THREAD

**Issue by bbakermmc** [DrJohnT/AzureDevOpsExtensionsForSqlServer#7]
Im confused as to what the target server is used for.  In the profile we set a connection string and db.  How are these other variables used?

**Comment by jaydsoni** [comment]
The target server is used to tell the task where it is deploying the script or a DACPAC file. I am not sure if it can read it from the connection string or not.

**Comment by DrJohnT** [comment]
@bbakermmc 
Yes, @jaydsoni  is correct, the target server is used to indicate where the DACPAC should be deployed.  The extension actually updates the connection string in the DAC Publish Profile you supply.  Of course, you may well have other settings in your DAC Publish Profile such as SqlCmd variables - which the extension can also overwrite for you.

The ultimate test of a good deployment pipeline is that the names of all the databases and cubes can be changed in the pipeline variables and everything will deploy correctly, the test will run and data can be loaded (if your have a test dataset).
