### ISSUE TITLE
What is the minimum requirement of SSMS

### ISSUE THREAD

**Issue by jaydsoni** [DrJohnT/AzureDevOpsExtensionsForSqlServer#8]
What is the minimum requirement of SSMS for the task "Deploy database DACPAC using a DAC Publish Profile"?

**Comment by DrJohnT** [comment]
There is no requirement for SSMS, only SqlPackage.exe as described on the component's page [DeployDatabase](https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.DeployDatabase)
